"""add_qc_columns_to_study_material_versions

Revision ID: 78cfdaa3ac8f
Revises: b4e8f2a1c3d5
Create Date: 2026-06-18 05:17:36.770717

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78cfdaa3ac8f"
down_revision: str | Sequence[str] | None = "b4e8f2a1c3d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "studymaterialversions",
        sa.Column(
            "qcfailedpermanently", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "studymaterialversions",
        sa.Column("qcresult", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("studymaterialversions", "qcresult")
    op.drop_column("studymaterialversions", "qcfailedpermanently")
    # ### end Alembic commands ###
