"""initial_tables

Revision ID: 8d53b9242a11
Revises:
Create Date: 2026-06-08 12:35:38.232967

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d53b9242a11"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "itadmins",
        sa.Column("itadminid", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("passwordhash", sa.String(length=255), nullable=False),
        sa.Column("fullname", sa.String(length=150), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("isactive", sa.Boolean(), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deletedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("itadminid"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "revokedtokens",
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("revokedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index(
        op.f("ix_revokedtokens_jti"), "revokedtokens", ["jti"], unique=False
    )
    op.create_table(
        "departments",
        sa.Column("departmentid", sa.UUID(), nullable=False),
        sa.Column("departmentname", sa.String(length=150), nullable=False),
        sa.Column("departmentcode", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("isactive", sa.Boolean(), nullable=False),
        sa.Column("createdby", sa.UUID(), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["createdby"], ["itadmins.itadminid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("departmentid"),
        sa.UniqueConstraint("departmentcode"),
    )
    op.create_table(
        "mentors",
        sa.Column("mentorid", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("passwordhash", sa.String(length=255), nullable=False),
        sa.Column("fullname", sa.String(length=150), nullable=False),
        sa.Column("designation", sa.String(length=100), nullable=False),
        sa.Column("departmentid", sa.UUID(), nullable=False),
        sa.Column("employeeid", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("profilepictureurl", sa.Text(), nullable=True),
        sa.Column("isactive", sa.Boolean(), nullable=False),
        sa.Column("createdby", sa.UUID(), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deletedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["createdby"], ["itadmins.itadminid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["departmentid"], ["departments.departmentid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("mentorid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("employeeid"),
    )
    op.create_table(
        "trainees",
        sa.Column("traineeid", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("passwordhash", sa.String(length=255), nullable=False),
        sa.Column("fullname", sa.String(length=150), nullable=False),
        sa.Column("employeeid", sa.String(length=50), nullable=True),
        sa.Column("departmentid", sa.UUID(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("profilepictureurl", sa.Text(), nullable=True),
        sa.Column("joiningdate", sa.Date(), nullable=True),
        sa.Column("isactive", sa.Boolean(), nullable=False),
        sa.Column("createdby", sa.UUID(), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deletedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["createdby"], ["itadmins.itadminid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["departmentid"], ["departments.departmentid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("traineeid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("employeeid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trainees")
    op.drop_table("mentors")
    op.drop_table("departments")
    op.drop_index(op.f("ix_revokedtokens_jti"), table_name="revokedtokens")
    op.drop_table("revokedtokens")
    op.drop_table("itadmins")
    # ### end Alembic commands ###
