"""add_new_schema_and_tables

Revision ID: ec1dd70e33e8
Revises: 8d53b9242a11
Create Date: 2026-06-09 06:46:52.651108

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec1dd70e33e8"
down_revision: str | Sequence[str] | None = "8d53b9242a11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ── 1. espaces (depends on: departments, mentors — both from initial migration) ──
    op.create_table(
        "espaces",
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("spacename", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("departmentid", sa.UUID(), nullable=False),
        sa.Column("mentorid", sa.UUID(), nullable=False),
        sa.Column("transferredtomentorid", sa.UUID(), nullable=True),
        sa.Column("defaultteachinginstruction", sa.Text(), nullable=True),
        sa.Column("invitecode", sa.String(length=20), nullable=True),
        sa.Column("ispublished", sa.Boolean(), nullable=False),
        sa.Column("isactive", sa.Boolean(), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("archivedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["departmentid"], ["departments.departmentid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["mentorid"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["transferredtomentorid"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("spaceid"),
        sa.UniqueConstraint("invitecode"),
    )

    # ── 2. traineenotificationreads (depends on: trainees only — independent of espaces) ──
    op.create_table(
        "traineenotificationreads",
        sa.Column("readid", sa.UUID(), nullable=False),
        sa.Column("traineeid", sa.UUID(), nullable=False),
        sa.Column("notificationtype", sa.String(length=20), nullable=False),
        sa.Column("notificationid", sa.UUID(), nullable=False),
        sa.Column("readat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["traineeid"], ["trainees.traineeid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("readid"),
        sa.UniqueConstraint(
            "traineeid",
            "notificationtype",
            "notificationid",
            name="uq_traineenotificationreads_trainee_type_notification",
        ),
    )
    op.create_index(
        "ix_traineenotificationreads_trainee_type",
        "traineenotificationreads",
        ["traineeid", "notificationtype"],
        unique=False,
    )

    # ── 3. topicnodes — created WITHOUT sourcepdfid FK to break the circular dependency ──
    #    sourcepdfid FK (→ referencematerials) is added after referencematerials exists (step 5).
    op.create_table(
        "topicnodes",
        sa.Column("nodeid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("parentid", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("orderindex", sa.Integer(), nullable=False),
        sa.Column("nodespecificinstruction", sa.Text(), nullable=True),
        sa.Column("isprimarylearningunit", sa.Boolean(), nullable=False),
        sa.Column("isactive", sa.Boolean(), nullable=False),
        sa.Column("createdby", sa.UUID(), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("sourcepdfid", sa.UUID(), nullable=True),  # FK added in step 5
        sa.Column("sourcesectionpath", sa.Text(), nullable=True),
        sa.Column("autogenerated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["createdby"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["parentid"], ["topicnodes.nodeid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("nodeid"),
    )
    op.create_index(
        "ix_topicnodes_space_parent_order",
        "topicnodes",
        ["spaceid", "parentid", "orderindex"],
        unique=False,
    )

    # ── 4. referencematerials (depends on: espaces, topicnodes, mentors — all now exist) ──
    op.create_table(
        "referencematerials",
        sa.Column("materialid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("nodeid", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("fileurl", sa.Text(), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("filesizebytes", sa.BigInteger(), nullable=True),
        sa.Column("mimetype", sa.String(length=100), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("isvisibletotrainees", sa.Boolean(), nullable=False),
        sa.Column("uploadedby", sa.UUID(), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deletedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["nodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["uploadedby"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("materialid"),
    )

    # ── 5. Now referencematerials exists — add the circular FK back to topicnodes ──
    op.create_foreign_key(
        "fk_topicnodes_sourcepdfid",
        "topicnodes",
        "referencematerials",
        ["sourcepdfid"],
        ["materialid"],
        ondelete="RESTRICT",
    )

    # ── 6. nodemedia (depends on: topicnodes, referencematerials, espaces, mentors) ──
    op.create_table(
        "nodemedia",
        sa.Column("mediaid", sa.UUID(), nullable=False),
        sa.Column("nodeid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("mediatype", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("fileurl", sa.Text(), nullable=True),
        sa.Column("orderindex", sa.Integer(), nullable=False),
        sa.Column("uploadedby", sa.UUID(), nullable=False),
        sa.Column("sourcepdfmaterialid", sa.UUID(), nullable=True),
        sa.Column("sourcepagenumber", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["nodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["sourcepdfmaterialid"],
            ["referencematerials.materialid"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["uploadedby"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("mediaid"),
    )

    # ── 7. pdfparsejobs (depends on: espaces, referencematerials, mentors) ──
    op.create_table(
        "pdfparsejobs",
        sa.Column("jobid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("materialid", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("rawjson", sa.Text(), nullable=True),
        sa.Column("cleanedskeleton", sa.Text(), nullable=True),
        sa.Column("errormessage", sa.Text(), nullable=True),
        sa.Column("initiatedby", sa.UUID(), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["initiatedby"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["materialid"], ["referencematerials.materialid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("jobid"),
    )

    # ── 8. spaceannouncements (depends on: espaces, mentors) ──
    op.create_table(
        "spaceannouncements",
        sa.Column("announcementid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("mentorid", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("eventtype", sa.String(length=50), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("isactive", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mentorid"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("announcementid"),
    )
    op.create_index(
        "ix_spaceannouncements_space_created",
        "spaceannouncements",
        ["spaceid", "createdat"],
        unique=False,
    )

    # ── 9. spacetrainees (depends on: espaces, trainees) ──
    op.create_table(
        "spacetrainees",
        sa.Column("spacetraineeid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("traineeid", sa.UUID(), nullable=False),
        sa.Column("joinedvia", sa.String(length=20), nullable=False),
        sa.Column("joinedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("isactive", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["traineeid"], ["trainees.traineeid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("spacetraineeid"),
        sa.UniqueConstraint(
            "spaceid", "traineeid", name="uq_spacetrainees_space_trainee"
        ),
    )

    # ── 10. studymaterialversions (depends on: topicnodes, espaces, referencematerials, mentors) ──
    op.create_table(
        "studymaterialversions",
        sa.Column("versionid", sa.UUID(), nullable=False),
        sa.Column("nodeid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("versionnumber", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("generationtype", sa.String(length=20), nullable=False),
        sa.Column("mentorfeedbackused", sa.Text(), nullable=True),
        sa.Column("referencematerialid", sa.UUID(), nullable=True),
        sa.Column("basedonversionid", sa.UUID(), nullable=True),
        sa.Column("llmmodelused", sa.String(length=100), nullable=True),
        sa.Column("promptsnapshot", sa.Text(), nullable=True),
        sa.Column("tokenusage", sa.Integer(), nullable=True),
        sa.Column("isactive", sa.Boolean(), nullable=False),
        sa.Column("ispublished", sa.Boolean(), nullable=False),
        sa.Column("publishedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("publishedby", sa.UUID(), nullable=True),
        sa.Column("createdby", sa.UUID(), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["basedonversionid"],
            ["studymaterialversions.versionid"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["createdby"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["nodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["publishedby"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["referencematerialid"],
            ["referencematerials.materialid"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("versionid"),
    )

    # ── 11. traineenodeprogress (depends on: trainees, topicnodes, espaces) ──
    op.create_table(
        "traineenodeprogress",
        sa.Column("progressid", sa.UUID(), nullable=False),
        sa.Column("traineeid", sa.UUID(), nullable=False),
        sa.Column("nodeid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("studymaterialviewed", sa.Boolean(), nullable=False),
        sa.Column("firstviewedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("lastviewedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("studymaterialreadpercent", sa.Integer(), nullable=False),
        sa.Column("studymaterialcompleted", sa.Boolean(), nullable=False),
        sa.Column("quizbestscore", sa.Float(), nullable=True),
        sa.Column("quizattemptcount", sa.Integer(), nullable=False),
        sa.Column("quizpassed", sa.Boolean(), nullable=False),
        sa.Column("chatsessioncount", sa.Integer(), nullable=False),
        sa.Column("completionstatus", sa.String(length=20), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["nodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["traineeid"], ["trainees.traineeid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("progressid"),
        sa.UniqueConstraint(
            "traineeid", "nodeid", name="uq_traineenodeprogress_trainee_node"
        ),
    )

    # ── 12. traineespaceprogress (depends on: trainees, espaces) ──
    op.create_table(
        "traineespaceprogress",
        sa.Column("spaceprogressid", sa.UUID(), nullable=False),
        sa.Column("traineeid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("totalnodes", sa.Integer(), nullable=False),
        sa.Column("completednodes", sa.Integer(), nullable=False),
        sa.Column("overallscoreavg", sa.Float(), nullable=True),
        sa.Column("lastactivityat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["traineeid"], ["trainees.traineeid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("spaceprogressid"),
        sa.UniqueConstraint(
            "traineeid", "spaceid", name="uq_traineespaceprogress_trainee_space"
        ),
    )

    # ── 13. quizzes (depends on: topicnodes, espaces, studymaterialversions, mentors) ──
    op.create_table(
        "quizzes",
        sa.Column("quizid", sa.UUID(), nullable=False),
        sa.Column("nodeid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("studymaterialversionid", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("totalquestions", sa.Integer(), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("ispublished", sa.Boolean(), nullable=False),
        sa.Column("publishedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("createdby", sa.UUID(), nullable=False),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updatedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["createdby"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["nodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["studymaterialversionid"],
            ["studymaterialversions.versionid"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("quizid"),
    )

    # ── 14. chatsessions (depends on: trainees, topicnodes, espaces, studymaterialversions) ──
    op.create_table(
        "chatsessions",
        sa.Column("sessionid", sa.UUID(), nullable=False),
        sa.Column("traineeid", sa.UUID(), nullable=False),
        sa.Column("nodeid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("studymaterialversionid", sa.UUID(), nullable=False),
        sa.Column("sessiontitle", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("totalmessages", sa.Integer(), nullable=False),
        sa.Column("contexttokencount", sa.Integer(), nullable=True),
        sa.Column("startedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("lastmessageat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("closedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["nodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["studymaterialversionid"],
            ["studymaterialversions.versionid"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["traineeid"], ["trainees.traineeid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("sessionid"),
    )

    # ── 15. pdfparsejobnodes (depends on: pdfparsejobs, topicnodes) ──
    op.create_table(
        "pdfparsejobnodes",
        sa.Column("previewnodeid", sa.UUID(), nullable=False),
        sa.Column("jobid", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("orderindex", sa.Integer(), nullable=False),
        sa.Column("mentoraction", sa.String(length=20), nullable=False),
        sa.Column("appliednodeid", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["appliednodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["jobid"], ["pdfparsejobs.jobid"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("previewnodeid"),
    )

    # ── 16. chatmessages (depends on: chatsessions, trainees, topicnodes) ──
    op.create_table(
        "chatmessages",
        sa.Column("messageid", sa.UUID(), nullable=False),
        sa.Column("sessionid", sa.UUID(), nullable=False),
        sa.Column("traineeid", sa.UUID(), nullable=False),
        sa.Column("nodeid", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tokencount", sa.Integer(), nullable=True),
        sa.Column("llmmodelused", sa.String(length=100), nullable=True),
        sa.Column("contextwindowsnapshot", sa.Text(), nullable=True),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("isdeleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["nodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["sessionid"], ["chatsessions.sessionid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["traineeid"], ["trainees.traineeid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("messageid"),
    )

    # ── 17. nodeeventnotifications (depends on: espaces, topicnodes, mentors, studymaterialversions, quizzes, referencematerials) ──
    op.create_table(
        "nodeeventnotifications",
        sa.Column("notificationid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("nodeid", sa.UUID(), nullable=False),
        sa.Column("eventtype", sa.String(length=60), nullable=False),
        sa.Column("triggeredby", sa.UUID(), nullable=False),
        sa.Column("relatedversionid", sa.UUID(), nullable=True),
        sa.Column("relatedquizid", sa.UUID(), nullable=True),
        sa.Column("relatedmaterialid", sa.UUID(), nullable=True),
        sa.Column("systemmessage", sa.Text(), nullable=False),
        sa.Column("mentorcustommessage", sa.Text(), nullable=True),
        sa.Column("createdat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["nodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["relatedmaterialid"],
            ["referencematerials.materialid"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["relatedquizid"], ["quizzes.quizid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["relatedversionid"],
            ["studymaterialversions.versionid"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["triggeredby"], ["mentors.mentorid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("notificationid"),
    )
    op.create_index(
        "ix_nodeeventnotifications_space_node_created",
        "nodeeventnotifications",
        ["spaceid", "nodeid", "createdat"],
        unique=False,
    )

    # ── 18. quizattempts (depends on: quizzes, trainees, espaces, topicnodes) ──
    op.create_table(
        "quizattempts",
        sa.Column("attemptid", sa.UUID(), nullable=False),
        sa.Column("quizid", sa.UUID(), nullable=False),
        sa.Column("traineeid", sa.UUID(), nullable=False),
        sa.Column("spaceid", sa.UUID(), nullable=False),
        sa.Column("nodeid", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("totalcorrect", sa.Integer(), nullable=True),
        sa.Column("totalwithhints", sa.Integer(), nullable=True),
        sa.Column("totalskipped", sa.Integer(), nullable=True),
        sa.Column("startedat", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("submittedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["nodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["quizid"], ["quizzes.quizid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["spaceid"], ["espaces.spaceid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["traineeid"], ["trainees.traineeid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("attemptid"),
    )

    # ── 19. quizquestions (depends on: quizzes, topicnodes) ──
    op.create_table(
        "quizquestions",
        sa.Column("questionid", sa.UUID(), nullable=False),
        sa.Column("quizid", sa.UUID(), nullable=False),
        sa.Column("nodeid", sa.UUID(), nullable=False),
        sa.Column("questiontext", sa.Text(), nullable=False),
        sa.Column("optiona", sa.Text(), nullable=False),
        sa.Column("optionb", sa.Text(), nullable=False),
        sa.Column("optionc", sa.Text(), nullable=True),
        sa.Column("optiond", sa.Text(), nullable=True),
        sa.Column("correctoption", sa.String(length=1), nullable=False),
        sa.Column("hint1", sa.Text(), nullable=True),
        sa.Column("hint2", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("orderindex", sa.Integer(), nullable=False),
        sa.Column("isactive", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["nodeid"], ["topicnodes.nodeid"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["quizid"], ["quizzes.quizid"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("questionid"),
    )

    # ── 20. quizquestionresponses (depends on: quizattempts, quizquestions, trainees) ──
    op.create_table(
        "quizquestionresponses",
        sa.Column("responseid", sa.UUID(), nullable=False),
        sa.Column("attemptid", sa.UUID(), nullable=False),
        sa.Column("questionid", sa.UUID(), nullable=False),
        sa.Column("traineeid", sa.UUID(), nullable=False),
        sa.Column("selectedoption", sa.String(length=1), nullable=True),
        sa.Column("iscorrect", sa.Boolean(), nullable=True),
        sa.Column("attemptcount", sa.Integer(), nullable=False),
        sa.Column("hintlevelreached", sa.Integer(), nullable=False),
        sa.Column("wasskipped", sa.Boolean(), nullable=False),
        sa.Column("waslocked", sa.Boolean(), nullable=False),
        sa.Column("respondedat", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attemptid"], ["quizattempts.attemptid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["questionid"], ["quizquestions.questionid"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["traineeid"], ["trainees.traineeid"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("responseid"),
        sa.UniqueConstraint(
            "attemptid", "questionid", name="uq_quizquestionresponses_attempt_question"
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop in reverse dependency order (leaf tables first)
    op.drop_table("quizquestionresponses")
    op.drop_table("quizquestions")
    op.drop_table("quizattempts")
    op.drop_index(
        "ix_nodeeventnotifications_space_node_created",
        table_name="nodeeventnotifications",
    )
    op.drop_table("nodeeventnotifications")
    op.drop_table("chatmessages")
    op.drop_table("quizzes")
    op.drop_table("pdfparsejobnodes")
    op.drop_table("chatsessions")
    op.drop_table("traineespaceprogress")
    op.drop_table("traineenodeprogress")
    op.drop_table("studymaterialversions")
    op.drop_table("spacetrainees")
    op.drop_index(
        "ix_spaceannouncements_space_created", table_name="spaceannouncements"
    )
    op.drop_table("spaceannouncements")
    op.drop_table("pdfparsejobs")
    op.drop_table("nodemedia")
    # Drop the circular FK on topicnodes before dropping referencematerials
    op.drop_constraint("fk_topicnodes_sourcepdfid", "topicnodes", type_="foreignkey")
    op.drop_table("referencematerials")
    op.drop_index("ix_topicnodes_space_parent_order", table_name="topicnodes")
    op.drop_table("topicnodes")
    op.drop_index(
        "ix_traineenotificationreads_trainee_type",
        table_name="traineenotificationreads",
    )
    op.drop_table("traineenotificationreads")
    op.drop_table("espaces")
