import uuid

from sqlalchemy import Column, String, Boolean, Text, Integer, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID, TIMESTAMP
from sqlalchemy.orm import relationship

from src.api.data.clients.postgres.database import Base
from src.api.utils.time import utc_now


class TopicNode(Base):
    __tablename__ = "topicnodes"

    nodeid = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    spaceid = Column(
        UUID(as_uuid=True),
        ForeignKey("espaces.spaceid", ondelete="RESTRICT"),
        nullable=False,
    )

    # NULL = root node; self-referential adjacency list for unbounded depth
    parentid = Column(
        UUID(as_uuid=True),
        ForeignKey("topicnodes.nodeid", ondelete="RESTRICT"),
        nullable=True,
    )

    title = Column(String(300), nullable=False)

    # 1 = Topic, 2 = Subtopic, 3+ = deep node; maintained by app on insert/reparent (EC-2)
    level = Column(Integer, nullable=False)

    # Sibling ordering within the same parent
    orderindex = Column(Integer, nullable=False, default=0)

    nodespecificinstruction = Column(Text, nullable=True)

    # Future-use only — does NOT drive any MVP logic (every node at every depth is a learning unit)
    isprimarylearningunit = Column(Boolean, nullable=False, default=False)

    isactive = Column(Boolean, nullable=False, default=True)

    createdby = Column(
        UUID(as_uuid=True),
        ForeignKey("mentors.mentorid", ondelete="RESTRICT"),
        nullable=False,
    )

    createdat = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        default=utc_now,
    )
    updatedat = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )

    # Phase 2A auto-tree fields — columns present in MVP schema, feature inactive until Phase 2A
    sourcepdfid = Column(
        UUID(as_uuid=True),
        ForeignKey("referencematerials.materialid", ondelete="RESTRICT"),
        nullable=True,
    )
    sourcesectionpath = Column(Text, nullable=True)
    autogenerated = Column(Boolean, nullable=False, default=False)

    __table_args__ = (
        Index(
            "ix_topicnodes_space_parent_order",
            "spaceid",
            "parentid",
            "orderindex",
        ),
    )

    space = relationship("ESpace", back_populates="topic_nodes")

    # Self-referential: parent node and its children
    parent = relationship(
        "TopicNode",
        remote_side="TopicNode.nodeid",
        foreign_keys=[parentid],
        back_populates="children",
    )
    children = relationship(
        "TopicNode",
        foreign_keys=[parentid],
        back_populates="parent",
    )

    created_by_mentor = relationship(
        "Mentor",
        foreign_keys=[createdby],
        back_populates="created_nodes",
    )

    source_pdf = relationship(
        "ReferenceMaterial",
        foreign_keys=[sourcepdfid],
    )