import uuid

from sqlalchemy import Boolean, Column, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import relationship

from src.api.data.clients.postgres.database import Base
from src.api.utils.time import utc_now


class TopicNode(Base):
    __tablename__ = "topicnodes"

    node_id = Column("nodeid", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    space_id = Column(
        "spaceid",
        UUID(as_uuid=True),
        ForeignKey("espaces.spaceid", ondelete="RESTRICT"),
        nullable=False,
    )

    # NULL = root node; self-referential adjacency list for unbounded depth
    parent_id = Column(
        "parentid",
        UUID(as_uuid=True),
        ForeignKey("topicnodes.nodeid", ondelete="RESTRICT"),
        nullable=True,
    )

    title = Column(String(300), nullable=False)

    # 1 = Topic, 2 = Subtopic, 3+ = deep node; maintained by app on insert/reparent (EC-2)
    level = Column(Integer, nullable=False)

    # Sibling ordering within the same parent
    order_index = Column("orderindex", Integer, nullable=False, default=0)

    node_specific_instruction = Column("nodespecificinstruction", Text, nullable=True)

    # Default teaching instruction for this node’s subtree. Typically set on root nodes; descendants inherit it unless they override it.
    tree_default_instruction = Column("treedefaultinstruction", Text, nullable=True)

    # Additive instruction for this node only — applied on top of inherited treedefaultinstruction
    # values from ancestors. NOT inherited by descendants.
    # Resolution priority (service layer):
    #   1. nodespecificinstruction (full override) — if set, use only this
    #   2. inherited treedefaultinstruction chain + nodeadditiveinstruction
    node_additive_instruction = Column("nodeadditiveinstruction", Text, nullable=True)

    # Future-use only — does NOT drive any MVP logic (every node at every depth is a learning unit)
    is_primary_learning_unit = Column(
        "isprimarylearningunit", Boolean, nullable=False, default=False
    )

    is_active = Column("isactive", Boolean, nullable=False, default=True)

    created_by = Column(
        "createdby",
        UUID(as_uuid=True),
        ForeignKey("mentors.mentorid", ondelete="RESTRICT"),
        nullable=False,
    )

    created_at = Column(
        "createdat",
        TIMESTAMP(timezone=True),
        nullable=False,
        default=utc_now,
    )
    updated_at = Column(
        "updatedat",
        TIMESTAMP(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )

    # Phase 2A auto-tree fields — columns present in MVP schema, feature inactive until Phase 2A
    source_pdf_id = Column(
        "sourcepdfid",
        UUID(as_uuid=True),
        ForeignKey("referencematerials.materialid", ondelete="RESTRICT"),
        nullable=True,
    )
    source_section_path = Column("sourcesectionpath", Text, nullable=True)
    auto_generated = Column("autogenerated", Boolean, nullable=False, default=False)

    __table_args__ = (
        Index(
            "ix_topicnodes_space_parent_order",
            "spaceid",
            "parentid",
            "orderindex",
        ),
    )

    space = relationship("ESpace", back_populates="topic_nodes")

    # Self-referential: parent node and its children
    parent = relationship(
        "TopicNode",
        remote_side="TopicNode.node_id",
        foreign_keys=[parent_id],
        back_populates="children",
    )
    children = relationship(
        "TopicNode",
        foreign_keys=[parent_id],
        back_populates="parent",
    )

    created_by_mentor = relationship(
        "Mentor",
        foreign_keys=[created_by],
        back_populates="created_nodes",
    )

    source_pdf = relationship(
        "ReferenceMaterial",
        foreign_keys=[source_pdf_id],
    )
